INSERT INTO first_level_divisions(Division_ID, Division, Create_Date, Created_By, Last_Update, Last_Updated_By, Country_ID)
VALUES (1, 'Alabama', NOW(), 'script', NOW(), 'script', 1),
	   (2, 'Arizona', NOW(), 'script', NOW(), 'script', 1),
       (3, 'Arkansas', NOW(), 'script', NOW(), 'script', 1),
       (4, 'California', NOW(), 'script', NOW(), 'script', 1),
       (5, 'Colorado', NOW(), 'script', NOW(), 'script', 1),
       (6, 'Connecticut', NOW(), 'script', NOW(), 'script', 1),
       (7, 'Delaware', NOW(), 'script', NOW(), 'script', 1),
       (8, 'District of Columbia', NOW(), 'script', NOW(), 'script', 1),
       (9, 'Florida', NOW(), 'script', NOW(), 'script', 1),
       (10, 'Georgia', NOW(), 'script', NOW(), 'script', 1),
       (11, 'Idaho', NOW(), 'script', NOW(), 'script', 1),
       (12, 'Illinois', NOW(), 'script', NOW(), 'script', 1),
       (13, 'Indiana', NOW(), 'script', NOW(), 'script', 1),
       (14, 'Iowa', NOW(), 'script', NOW(), 'script', 1),
       (15, 'Kansas', NOW(), 'script', NOW(), 'script', 1),
       (16, 'Kentucky', NOW(), 'script', NOW(), 'script', 1),
       (17, 'Louisiana', NOW(), 'script', NOW(), 'script', 1),
       (18, 'Maine', NOW(), 'script', NOW(), 'script', 1),
       (19, 'Maryland', NOW(), 'script', NOW(), 'script', 1),
       (20, 'Massachusetts', NOW(), 'script', NOW(), 'script', 1),
       (21, 'Michigan', NOW(), 'script', NOW(), 'script', 1),
       (22, 'Minnesota', NOW(), 'script', NOW(), 'script', 1),
       (23, 'Mississippi', NOW(), 'script', NOW(), 'script', 1),
       (24, 'Missouri', NOW(), 'script', NOW(), 'script', 1),
       (25, 'Montana', NOW(), 'script', NOW(), 'script', 1),
       (26, 'Nebraska', NOW(), 'script', NOW(), 'script', 1),
       (27, 'Nevada', NOW(), 'script', NOW(), 'script', 1),
       (28, 'New Hampshire', NOW(), 'script', NOW(), 'script', 1),
       (29, 'New Jersey', NOW(), 'script', NOW(), 'script', 1),
       (30, 'New Mexico', NOW(), 'script', NOW(), 'script', 1),
       (31, 'New York', NOW(), 'script', NOW(), 'script', 1),
       (32, 'North Carolina', NOW(), 'script', NOW(), 'script', 1),
       (33, 'North Daktoa', NOW(), 'script', NOW(), 'script', 1),
       (34, 'Ohio', NOW(), 'script', NOW(), 'script', 1),
       (35, 'Oklahoma', NOW(), 'script', NOW(), 'script', 1),
       (36, 'Oregon', NOW(), 'script', NOW(), 'script', 1),
       (37, 'Pennsylvania', NOW(), 'script', NOW(), 'script', 1),
       (38, 'Rhode Island', NOW(), 'script', NOW(), 'script', 1),
       (39, 'South Carolina', NOW(), 'script', NOW(), 'script', 1),
       (40, 'South Dakota', NOW(), 'script', NOW(), 'script', 1),
       (41, 'Tennessee', NOW(), 'script', NOW(), 'script', 1),
       (42, 'Texas', NOW(), 'script', NOW(), 'script', 1),
       (43, 'Utah', NOW(), 'script', NOW(), 'script', 1),
       (44, 'Vermont', NOW(), 'script', NOW(), 'script', 1),
       (45, 'Virginia', NOW(), 'script', NOW(), 'script', 1),
       (46, 'Washington', NOW(), 'script', NOW(), 'script', 1),
       (47, 'West Virginia', NOW(), 'script', NOW(), 'script', 1),
       (48, 'Wisconsin', NOW(), 'script', NOW(), 'script', 1),
       (49, 'Wyoming', NOW(), 'script', NOW(), 'script', 1),
       (52, 'Hawaii', NOW(), 'script', NOW(), 'script', 1),
       (54, 'Alaska', NOW(), 'script', NOW(), 'script', 1),
       (60, 'Northwest Territory', NOW(), 'script', NOW(), 'script', 3),
       (61, 'Alberta', NOW(), 'script', NOW(), 'script', 3),
       (62, 'British Columbia', NOW(), 'script', NOW(), 'script', 3),
       (63, 'Manitoba', NOW(), 'script', NOW(), 'script', 3),
       (64, 'New Brunswick', NOW(), 'script', NOW(), 'script', 3),
       (65, 'Nova Scotia', NOW(), 'script', NOW(), 'script', 3),
       (66, 'Prince Edward Island', NOW(), 'script', NOW(), 'script', 3),
       (67, 'Ontario', NOW(), 'script', NOW(), 'script', 3),
       (68, 'Quebec', NOW(), 'script', NOW(), 'script', 3),
       (69, 'Saskatchewan', NOW(), 'script', NOW(), 'script', 3),
       (70, 'Nunavut', NOW(), 'script', NOW(), 'script', 3),
       (71, 'Yukon', NOW(), 'script', NOW(), 'script', 3),
       (72, 'Newfoundland', NOW(), 'script', NOW(), 'script', 3),
       (101, 'England', NOW(), 'script', NOW(), 'script', 2),
       (102, 'Wales', NOW(), 'script', NOW(), 'script', 2),
       (103, 'Scotland', NOW(), 'script', NOW(), 'script', 2),
       (104, 'Northern Ireland', NOW(), 'script', NOW(), 'script', 2);
       